### PR TITLE
Feature/update content

### PR DESCRIPTION
**Pull request by emilsomm**
- started new development environment with `.scss`
- set up Hugo preprocessing
- relink fonts with `aepp-components` library
- introduce `$variables`
- update and restyle features section
- add handle funds section
- tweak `.btn` styles

### CODE REVIEW

**Comment by emilsomm** [comment]
The travis build does not recognise a function in Hugo, used to pull in the `scss` files. When i remove this it builds ok, but it doesn't work with it. 

Locally it builds fine with Hugo, and how I use this function is an example from the `Hugo docs`: 
https://gohugo.io/hugo-pipes/introduction/#go-pipes

**Comment by emilsomm** [comment]
I copied the styles from the  `/resources` folder and insert them using the previous method 
`<link rel="stylesheet" href="{{"/css/styles-min.css" | relURL }}">`

Travis is no longer complaining 😃 

But it would be nice to know why the Hugo pipe function is not working as it should...?

**Comment by dadaphl** [comment]
I'd prefer to use a version of hugo that does not have external dependencies. I think hugo should be responsible for one thing only; transform markdown to html.

**Review by emilsomm — COMMENTED** [review]
The file was corrupted during download, fixed in commit ace7e22

**Review by dadaphl — APPROVED** [review]
LGTM

**Pull request merged**
