### PR TITLE
Naming changes, please carefully review and don’t merge until further notice (final naming decisions).

### PR DESCRIPTION
**Pull request by andi-apeunit**

### CODE REVIEW

**Comment by dadaphl** [comment]
Can you please give some explanation what this is all about and which part deserves careful review?

**Comment by andi-apeunit** [comment]
Naming changes throughout the whole website:

Aeternity -> æternity
aepp -> æpp

Identity Manager -> Base æpp
Address Book -> Addresses
Messenger -> Messages

identities -> accounts
Test Net -> testnet

Also I renamed messenger.md to messages.md and messenger.svg to messages.svg, plus the new domain for Base æpp will be base.aepps.com and no longer identity.aepps.com …

Careful review means: please check for typos and if I linked the renamed files correctly.

**Comment by raymundjacobs** [comment]
@andi-apeunit why is there in ../img/aepps/messages/2.png a hamburger button & in  ../img/aepps/messages/3.png an arrow in the upper right corner? These are the same screens right?

**Comment by andi-apeunit** [comment]
Thanks Ray, the images needed to be updated with the newer ones from Zeplin … done. Also added new images for Addresses. Renamed Chærity to Answers for AE.

NOTE: We should wait until Denis renamed all the æpps in the Base æpp, then this PR should be merged if everything was checked by more than my two eyes.

**Pull request closed without merging**
